"""Shared data models used across all strategies and core modules."""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum


class Side(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderStatus(str, Enum):
    PENDING = "PENDING"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"


class PositionStatus(str, Enum):
    OPEN = "OPEN"
    PARTIAL_EXIT = "PARTIAL_EXIT"
    CLOSED = "CLOSED"


class SignalType(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    EXIT = "EXIT"


@dataclass
class Candle:
    """OHLCV candle for any timeframe."""
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: int
    token: str = ""
    symbol: str = ""

    @property
    def typical_price(self) -> float:
        return (self.high + self.low + self.close) / 3


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    signal_type: SignalType
    symbol: str
    token: str
    price: float
    strategy_name: str
    timestamp: datetime = field(default_factory=datetime.now)
    quantity: int = 0
    stop_loss: float = 0.0
    target: float = 0.0
    reason: str = ""
    indicators: dict = field(default_factory=dict)  # e.g. {"rsi": 18.5, "atr": 4.2}


@dataclass
class Order:
    """Order to be placed with the broker."""
    order_id: str = ""
    trade_id: str = ""
    symbol: str = ""
    token: str = ""
    side: Side = Side.BUY
    quantity: int = 0
    price: float = 0.0
    order_type: str = "LIMIT"  # LIMIT or STOPLOSS_MARKET
    product_type: str = "MIS"  # MIS (intraday) or CARRYFORWARD (F&O)
    exchange: str = "NSE"
    status: OrderStatus = OrderStatus.PENDING
    strategy_name: str = ""
    timestamp: datetime = field(default_factory=datetime.now)


@dataclass
class Position:
    """Open position tracked by the engine."""
    trade_id: str
    symbol: str
    token: str
    side: Side
    quantity: int
    entry_price: float
    entry_time: datetime
    strategy_name: str
    stop_loss: float = 0.0
    remaining_quantity: int = 0  # For partial exits
    realized_pnl: float = 0.0
    status: PositionStatus = PositionStatus.OPEN
    entry_candle_count: int = 0  # For time-stop tracking
    sector: str = ""
    indicators: dict = field(default_factory=dict)

    def __post_init__(self):
        if self.remaining_quantity == 0:
            self.remaining_quantity = self.quantity

    @property
    def unrealized_pnl_per_unit(self) -> float:
        """Needs current price — returns per-unit P&L direction multiplier."""
        return 1.0 if self.side == Side.BUY else -1.0
